#language: php
checks:
  php: true
filter:
  excluded_paths:
    - tests
build:
  nodes:
    analysis:
      environment:
        php: 7.4
        postgresql: true
        redis: true
        mongodb: true
      tests:
        override:
            - phpcs-run src
            -
                command: php -m -1 vendor/bin/phpstan analyze --error-format=checkstyle | sed '/^\s*$/d' > phpstan-checkstyle.xml
                analysis:
                    file: phpstan-checkstyle.xml
                    format: 'general-checkstyle'
            - php-scrutinizer-run

