name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      redis:
        image: redis:6.0
      mongo:
        image: mongo:4.2-bionic
      memcached:
        image: memcached:1.6

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.2
            composer: '--prefer-lowest'
            desc: "Lowest versions"
          - php: 7.4
            composer: '--prefer-lowest'
            desc: "Lowest versions"
          - php: 7.2
          - php: 7.3
          - php: 7.4
            coverage: '--coverage-clover /tmp/clover.xml'
          - php: 8.0
    name: PHP ${{ matrix.php }} ${{ matrix.desc }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Create MySQL cache database
      run: php -r "mysqli_connect('localhost')->multi_query('CREATE DATABASE cache; CREATE TABLE cache.cache (k varchar(255) NOT NULL, v text NOT NULL, t int(11) NOT NULL, PRIMARY KEY (k)) ENGINE=InnoDB DEFAULT CHARSET=utf8;');"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress ${{ matrix.composer }}

    - name: Run PHPUnit
      run: vendor/bin/phpunit ${{ matrix.coverage }}

    - name: Upload coverage to Scrutinizer
      if: ${{ matrix.coverage }}
      run: >
        wget https://scrutinizer-ci.com/ocular.phar -O "/tmp/ocular.phar" &&
        php "/tmp/ocular.phar" code-coverage:upload --format=php-clover /tmp/clover.xml
